version: "2.4"

#networks:
#  motion2nx-net:
#    driver: bridge

services:
  smpc-server0:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../logs:/usr/share/app/logs
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw

    restart: no
      #    networks:
      #- motion2nx-net
    network_mode: "host"
    ports:
      # cs0_port_model_receiver
      - "4016:4016"
      # cs0_port_inference
      - "4020:4020"
      # relu0_port_inference
      - "4023:4023"
      # cs0_port_image_receiver
      - "4025:4025"
    #mem_limit: 600m
    #cpus: 0.750
    mem_limit: 3300m
    cpus: 1.7
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/MultiCNN/ && ./MUL_helpernode_server0_cnn.sh c && while (true);  do  sleep 10; done"

  # SMPC server 1
  smpc-server1:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw
      - ../../../../logs:/usr/share/app/logs
    restart: no
    network_mode:
      "host"
      # - motion2nx-net
    ports:
      # cs1_port_model_receiver
      - "4017:4017"
      # cs1_port_inference
      - "4021:4021"
      # relu1_port_inference
      - "4024:4024"
      # cs1_port_image_receiver
      - "4026:4026"
    #mem_limit: 600m
    mem_limit: 3300m 
    cpus: 1.7
    #cpus: 0.750
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/MultiCNN/ && ./MUL_helpernode_server1_cnn.sh c && while (true);  do  sleep 10; done"

  # SMPC server 2 - helpernode server
  smpc-server2:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw
      - ../../../../logs:/usr/share/app/logs
    restart: no
    network_mode: host
    # networks:
    #   - motion2nx-net
    ports:
      # helpernode_port_inference
      - "4022:4022"
    mem_limit: 600m
    cpus: 0.75
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/MultiCNN/ && ./MUL_helpernode_server2_cnn.sh c && while (true);  do  sleep 10; done"
volumes:
  smpc-server1-volume:
  smpc-server0-volume:
  smpc-server2-volume:
