version: "2.4"

#networks:
#  motion2nx-net:
#    driver: bridge

services:
  smpc-server0:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../logs:/usr/share/app/logs
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw

    restart: no
      #    networks:
      #- motion2nx-net
    network_mode: "host"
    ports:
      # cs0_port_model_receiver
      - "4005:4005"
      # cs0_port_inference
      - "4009:4009"
      # relu0_port_inference
      - "4012:4012"
      # cs0_port_image_receiver
      - "4014:4014"
    #mem_limit: 600m
    #cpus: 0.750
    mem_limit: 7000m
    #cpus: 1.7
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/Pneumonia/ && ./helpernode_server0_pn.sh && while (true);  do  sleep 10; done"

  # SMPC server 1
  smpc-server1:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw
      - ../../../../logs:/usr/share/app/logs
    restart: no
    network_mode:
      "host"
      # - motion2nx-net
    ports:
      # cs1_port_model_receiver
      - "4006:4006"
      # cs1_port_inference
      - "4010:4010"
      # relu1_port_inference
      - "4013:4013"
      # cs1_port_image_receiver
      - "4015:4015"
    #mem_limit: 600m
    mem_limit: 8000m 
    #cpus: 1.7
    #cpus: 0.750
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/Pneumonia/ && ./helpernode_server1_pn.sh && while (true);  do  sleep 10; done"

  # SMPC server 2 - helpernode server
  smpc-server2:
    image: ghcr.io/datakaveri/motion2nx:local
    volumes:
      - ../../../../config_files:/usr/share/app/config_files:ro
      - ../../../../scripts:/usr/share/app/scripts:rw
      - ../../../../logs:/usr/share/app/logs
    restart: no
    network_mode: host
    # networks:
    #   - motion2nx-net
    ports:
      # helpernode_port_inference
      - "4011:4011"
    mem_limit: 2000m
    #cpus: 0.75
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: bash -c "cd scripts/ServerModel_Architecture/HelperNode/Pneumonia/ && ./helpernode_server2_pn.sh && while (true);  do  sleep 10; done"
volumes:
  smpc-server1-volume:
  smpc-server0-volume:
  smpc-server2-volume:
